// <auto-generated />
namespace TicketDesk.Web.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addDB24022020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDB24022020));
        
        string IMigrationMetadata.Id
        {
            get { return "202002240349204_addDB24022020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
